const mongoose = require('mongoose')
const Schema = mongoose.Schema

const vReportPro = new Schema({


    serial_no: { type: String, required: [true, 'Please enter Value.'] },
    selected_bank_id: { type: String, required: [true, 'Please enter Value.'] },
    selected_branch_id: { type: String, required: [true, 'Please enter Value.'] },
    name_of_applicant: { type: String, required: [true, 'Please enter Value.'] },
    property_address: { type: String, required: [true, 'Please enter Value.'] },
    area_details: { type: String, required: [true, 'Please enter Value.'] },
    proposed_buyer: { type: String, required: [true, 'Please enter Value.'] },
    loan_application_number: { type: String, required: [true, 'Please enter Value.'] },
    legal_address_of_property: { type: String, required: [true, 'Please enter Value.'] },
    date_of_inspection: { type: Date, required: [true, 'Please enter Value.'] },
    purpose_of_inspection: { type: String, required: [true, 'Please enter Value.'] },
    ward_no: { type: String, required: [true, 'Please enter Value.'] },
    vicinity: { type: String, required: [true, 'Please enter Value.'] },
    plot_site: { type: String, required: [true, 'Please enter Value.'] },
    pro_type: { type: String, required: [true, 'Please enter Value.'] },
    conditions_of_road: { type: String, required: [true, 'Please enter Value.'] },
    nearest_landmark: { type: String, required: [true, 'Please enter Value.'] },
    local_transport: { type: String, required: [true, 'Please enter Value.'] },
    local_transport_other: { type: String, required: [true, 'Please enter Value.'] },
    pro_identified_through: { type: String, required: [true, 'Please enter Value.'] },
    usage_entire_pro: { type: String, required: [true, 'Please enter Value.'] },
    additional_amenities: { type: String, required: [true, 'Please enter Value.'] },
    type_of_premises: { type: String, required: [true, 'Please enter Value.'] },
    occupied_by: { type: String, required: [true, 'Please enter Value.'] },
    name_of_occupant: { type: String, required: [true, 'Please enter Value.'] },
    property_rented: { type: String, required: [true, 'Please enter Value.'] },
    if_relative: { type: String, required: [true, 'Please enter Value.'] },
    if_rented: { type: String, required: [true, 'Please enter Value.'] },
    north_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    south_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    east_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    west_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    type_of_structure: { type: String, required: [true, 'Please enter Value.'] },
    no_of_floors: { type: String, required: [true, 'Please enter Value.'] },
    no_of_dwelling: { type: String, required: [true, 'Please enter Value.'] },
    no_of_wings: { type: String, required: [true, 'Please enter Value.'] },
    no_of_lifts: { type: String, required: [true, 'Please enter Value.'] },
    construction_year: { type: String, required: [true, 'Please enter Value.'] },
    future_life: { type: String, required: [true, 'Please enter Value.'] },
    age_of_property: { type: String, required: [true, 'Please enter Value.'] },
    beam_column: { type: String, required: [true, 'Please enter Value.'] },
    appearance_maintenance: { type: String, required: [true, 'Please enter Value.'] },
    common_remarks: { type: String, required: [true, 'Please enter Value.'] },
    finishing: { type: String, required: [true, 'Please enter Value.'] },
    roofing_terracing: { type: String, required: [true, 'Please enter Value.'] },
    no_of_lift: { type: String, required: [true, 'Please enter Value.'] },
    constr_per_approved: { type: String, required: [true, 'Please enter Value.'] },
    details_approved_plans: { type: String, required: [true, 'Please enter Value.'] },
    approval_date: { type: Date, required: [true, 'Please enter Value.'] },
    use_permission: { type: String, required: [true, 'Please enter Value.'] },
    violations_observed: { type: String, required: [true, 'Please enter Value.'] },
    local_byelaws: { type: String, required: [true, 'Please enter Value.'] },
    situated_floor_no: { type: String, required: [true, 'Please enter Value.'] },
    quality_fittings: { type: String, required: [true, 'Please enter Value.'] },
    Internal_composition: { type: String, required: [true, 'Please enter Value.'] },
    flooring: { type: String, required: [true, 'Please enter Value.'] },
    built_up_area: { type: String, required: [true, 'Please enter Value.'] },
    loading_sbua: { type: String, required: [true, 'Please enter Value.'] },
    approved_rates: { type: String, required: [true, 'Please enter Value.'] },
    final_value: { type: String, required: [true, 'Please enter Value.'] },
    recommended_rate: { type: String, required: [true, 'Please enter Value.'] },
    land_area: { type: String, required: [true, 'Please enter Value.'] },
    current_rates_for_land: { type: String, required: [true, 'Please enter Value.'] },
    land_recommended_rate: { type: String, required: [true, 'Please enter Value.'] },
    land_value: { type: String, required: [true, 'Please enter Value.'] },
    bua_premises: { type: String, required: [true, 'Please enter Value.'] },
    construction_cost: { type: String, required: [true, 'Please enter Value.'] },
    total_value_const: { type: String, required: [true, 'Please enter Value.'] },
    depreciate_value_const: { type: String, required: [true, 'Please enter Value.'] },
    total_valuation: { type: String, required: [true, 'Please enter Value.'] },
    say: { type: String, required: [true, 'Please enter Value.'] },
    remarks: { type: String, required: [true, 'Please enter Value.'] },
    images: { type: String, required: [true, 'Please enter Value.'] },
    link: { type: String, required: [true, 'Please enter Value.'] },
    updated_at: { type: Date, default: Date.now },
    created_at: { type: Date, default: Date.now }




})
module.exports = mongoose.model('vreportpro', vReportPro)
