const mongoose = require('mongoose')
const Schema = mongoose.Schema

const vReport = new Schema({

    serial_no: { type: String, required: [true, 'Please enter Value.'] },
    selected_bank_id: { type: String, required: [true, 'Please enter Value.'] },
    selected_branch_id: { type: String, required: [true, 'Please enter Value.'] },
    name_of_customer: { type: String, required: [true, 'Please enter Value.'] },
    customer_id: { type: String, required: [true, 'Please enter Value.'] },
    purpose_of_valuation: { type: String, required: [true, 'Please enter Value.'] },
    location: { type: String, required: [true, 'Please enter Value.'] },
    date_of_valuation: { type: Date, required: [true, 'Please enter Value.'] },
    estimated_market_value: { type: String, required: [true, 'Please enter Value.'] },
    documents_provided: { type: String, required: [true, 'Please enter Value.'] },
    documents_provided_other: { type: String, required: [true, 'Please enter Value.'] },
    revenue_survey_no: { type: String, required: [true, 'Please enter Value.'] },
    fp_no: { type: String, required: [true, 'Please enter Value.'] },
    tps_no: { type: String, required: [true, 'Please enter Value.'] },
    op_no: { type: String, required: [true, 'Please enter Value.'] },
    flat_no: { type: String, required: [true, 'Please enter Value.'] },
    mouje: { type: String, required: [true, 'Please enter Value.'] },
    society_name: { type: String, required: [true, 'Please enter Value.'] },
    landmark: { type: String, required: [true, 'Please enter Value.'] },
    taluka: { type: String, required: [true, 'Please enter Value.'] },
    district: { type: String, required: [true, 'Please enter Value.'] },
    local_transport: { type: String, required: [true, 'Please enter Value.'] },
    local_transport_other: { type: String, required: [true, 'Please enter Value.'] },
    distance_to_city_center: { type: String, required: [true, 'Please enter Value.'] },
    class_of_locality: { type: String, required: [true, 'Please enter Value.'] },
    quality_of_infrastructure: { type: String, required: [true, 'Please enter Value.'] },
    north_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    south_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    east_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    west_boundarie: { type: String, required: [true, 'Please enter Value.'] },
    boundaries_in_doc: { type: String, required: [true, 'Please enter Value.'] },
    topographical_condition: { type: String, required: [true, 'Please enter Value.'] },
    status_of_land: { type: String, required: [true, 'Please enter Value.'] },
    type_of_property: { type: String, required: [true, 'Please enter Value.'] },
    approved_usage: { type: String, required: [true, 'Please enter Value.'] },
    actual_usage: { type: String, required: [true, 'Please enter Value.'] },
    type_of_structure: { type: String, required: [true, 'Please enter Value.'] },
    no_of_floors: { type: String, required: [true, 'Please enter Value.'] },
    occupancy_details: { type: String, required: [true, 'Please enter Value.'] },
    property_connection: { type: String, required: [true, 'Please enter Value.'] },
    proximity: { type: String, required: [true, 'Please enter Value.'] },
    development_area: { type: String, required: [true, 'Please enter Value.'] },
    approval_details: { type: String, required: [true, 'Please enter Value.'] },
    construction_details: { type: String, required: [true, 'Please enter Value.'] },
    usages_of_pro: { type: String, required: [true, 'Please enter Value.'] },
    building_plan: { type: String, required: [true, 'Please enter Value.'] },
    side_margin: { type: String, required: [true, 'Please enter Value.'] },
    front_margin: { type: String, required: [true, 'Please enter Value.'] },
    quality_of_construction: { type: String, required: [true, 'Please enter Value.'] },
    maintenance_of_property: { type: String, required: [true, 'Please enter Value.'] },
    current_life_structure: { type: String, required: [true, 'Please enter Value.'] },
    estimated_life_structure: { type: String, required: [true, 'Please enter Value.'] },
    recommended_rate_flat: { type: String, required: [true, 'Please enter Value.'] },
    value_of_flat: { type: String, required: [true, 'Please enter Value.'] },
    value_of_terrace: { type: String, required: [true, 'Please enter Value.'] },
    total_value: { type: String, required: [true, 'Please enter Value.'] },
    say: { type: String, required: [true, 'Please enter Value.'] },
    stage_of_const: { type: String, required: [true, 'Please enter Value.'] },
    work_complited: { type: String, required: [true, 'Please enter Value.'] },
    disbursement_recommended: { type: String, required: [true, 'Please enter Value.'] },
    date_of_pro_visit: { type: Date, required: [true, 'Please enter Value.'] },
    government_rates: { type: String, required: [true, 'Please enter Value.'] },
    valuation_property: { type: String, required: [true, 'Please enter Value.'] },
    rent_value: { type: String, required: [true, 'Please enter Value.'] },
    remarks: { type: String, required: [true, 'Please enter Value.'] },
    images: { type: String, required: [true, 'Please enter Value.'] },
    google_map: { type: String, required: [true, 'Please enter Value.'] },
    google_map2: { type: String, required: [true, 'Please enter Value.'] },
    link: { type: String, required: [true, 'Please enter Value.'] },
    updated_at: { type: Date, default: Date.now },
    created_at: { type: Date, default: Date.now }

})
module.exports = mongoose.model('vreport', vReport)
